name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"        # Example: triggers on version tags like v1.0.0, v2.1.3, etc.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build Chain Node
        run: |
          cd chain
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Copy node binary into docker folder
        run: |
          cp chain/build/rxrevoltchain docker

      - name: Build Docker Image
        run: |
          cd docker
          docker build -t rxrevolt-chain-node .

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag rxrevolt-chain-node:latest docker.io/rxrevolt/rxrevolt-chain-node:${{ github.ref_name }}
          docker push docker.io/rxrevolt/rxrevolt-chain-node:${{ github.ref_name }}
