name: Continuous Integration

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true  # Ensures the submodules are also checked out

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install & Build Web Client
        run: |
          cd client/web
          npm install
          npm run build

      - name: Install & Build Electron Client
        run: |
          cd client/electron
          npm install
          npm run build

      - name: Build Chain Node (CMake)
        run: |
          cd chain
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run Tests (Placeholder)
        run: |
          # Insert your real test scripts/commands here
          echo "Running unit tests..."
          # For example:
          # cd client/web && npm test
          # cd ../electron && npm test
          # Or any other submodules with test suites
          echo "Tests completed!"
